export const languageToRepresentation = {
  English: {
    icon: "🇬🇧",
    key: "en",
    actionHeaderTranslation: {
      goToShelter: "enter the security room immediately",
      stayInShelter: "stay in the security room",
      stayNearByShelter: "stay close to the bunker",
      ShelterOut: "You can get out of the bunker",
      friendlyFire: "Sounds of the Israeli army",
      freeText: "free text",
    },
  },
  Filipino: {
    icon: "🇵🇭",
    key: "tl",
    actionHeaderTranslation: {
      goToShelter: "pumasok agad sa security room",
      stayInShelter: "manatili sa silid ng seguridad",
      stayNearByShelter: "manatili malapit sa bunker",
      ShelterOut: "Posibleng umalis sa security room",
      friendlyFire: "Tunog ng hukbo ng Israel",
      freeText: "Libreng Teksto",
    },
  },
  Hindi: {
    icon: "🇮🇳",
    key: "hi",
    actionHeaderTranslation: {
      goToShelter: "आपको तुरंत सुरक्षा कक्ष में प्रवेश करना होगा",
      stayInShelter: "सुरक्षा कक्ष में रहें",
      stayNearByShelter: "बंकर के करीब रहो",
      ShelterOut: "सुरक्षा कक्ष छोड़ना संभव है",
      friendlyFire: "इजरायली सेना की गोलीबारी",
      freeText: "फ्री टेक्स्ट",
    },
  },
  Uzbek: {
    icon: "🇺🇿",
    key: "uz",
    actionHeaderTranslation: {
      goToShelter: "darhol xavfsizlik xonasiga kiring",
      stayInShelter: "xavfsizlik xonasida qoling",
      stayNearByShelter: "bunkerga yaqin turing",
      ShelterOut: "Siz bunkerdan chiqib ketishingiz mumkin.",
      friendlyFire: "Isroil armiyasining tovushlari",
      freeText: "Bepul matn",
    },
  },
  russian: {
    icon: "🇷🇺",
    key: "ru",
    actionHeaderTranslation: {
      goToShelter: "немедленно проследовать в бомбоубежище",
      stayInShelter: "оставаться в бомбоубежище",
      stayNearByShelter: "оставайся рядом с бункером",
      ShelterOut: "Вы можете покинуть бомбоубежище",
      friendlyFire: "Звуки израильской армии",
      freeText: "Открытый текст",
    },
  },
  thai: {
    icon: "🇹🇭",
    key: "th",
    actionHeaderTranslation: {
      goToShelter: "คุณต้องเข้าไปในหลุมหลบภัยตอนนี้ทันที",
      stayInShelter: "อย่าออกจากบังเกอร์",
      stayNearByShelter: "อยู่ใกล้บังเกอร์",
      ShelterOut: "คุณสามารถออกจากบังเกอร์ได้",
      friendlyFire: "กองทัพอิสราเอลยิง",
      freeText: "ข้อความฟรี",
    },
  },
  Arabic: {
    icon: "🇸🇦",
    key: "ar",
    actionHeaderTranslation: {
      goToShelter: "ابق على مقربة من المخبأ",
      stayInShelter: "البقاء في غرفة الأمن",
      stayNearByShelter: "ابق على مقربة من المخبأ",
      ShelterOut: "يمكنك الخروج من المخبأ.",
      friendlyFire: "نيران الجيش الإسرائيلي",
      freeText: "نص حر",
    },
  },
};
